#!/usr/bin/env node
// Generates src/ldraw/colors.generated.ts from the library's LDConfig.ldr.
//
// LDrawLoader reads LDConfig at runtime for materials, but the UI also needs
// human colour names ("Bright Light Orange", not "code 191") and swatch hexes
// for the parts bin and inspector. Rather than parse LDConfig twice in the
// browser, we bake the table in at setup time.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { PUBLIC_LDRAW_DIR, SRC_DIR } from "./lib/paths.mjs";

const SOURCE = path.join(PUBLIC_LDRAW_DIR, "LDConfig.ldr");
const OUT = path.join(SRC_DIR, "ldraw", "colors.generated.ts");

const COLOUR_PREFIX = /^0\s+!COLOUR\s+/i;
const COLOUR_DIRECTIVE = /^0\s+!COLOUR/i;
const WHITESPACE = /\s+/;
const LINE_BREAK = /\r\n|\r|\n/;

/** `0 !COLOUR <name> CODE <n> VALUE <#rgb> EDGE <#rgb> [ALPHA <n>] [CHROME|METAL|PEARLESCENT|RUBBER|MATTE_METALLIC]` */
function parseColour(line) {
  const body = line.replace(COLOUR_PREFIX, "").trim();
  const tokens = body.split(WHITESPACE);
  const name = tokens.shift();
  if (!name) {
    return null;
  }

  const entry = { name: name.replace(/_/g, " ") };
  for (let i = 0; i < tokens.length; i += 1) {
    const key = tokens[i].toUpperCase();
    const value = tokens[i + 1];
    switch (key) {
      case "CODE":
        entry.code = Number(value);
        i += 1;
        break;
      case "VALUE":
        entry.hex = value?.toUpperCase();
        i += 1;
        break;
      case "EDGE":
        entry.edge = value?.toUpperCase();
        i += 1;
        break;
      case "ALPHA":
        entry.alpha = Number(value);
        i += 1;
        break;
      case "CHROME":
      case "METAL":
      case "PEARLESCENT":
      case "RUBBER":
      case "MATTE_METALLIC":
        entry.finish = key.toLowerCase();
        break;
      default:
        break;
    }
  }
  return Number.isFinite(entry.code) && entry.hex ? entry : null;
}

async function main() {
  let text;
  try {
    text = await readFile(SOURCE, "utf8");
  } catch (cause) {
    throw new Error(`missing ${SOURCE}. Run: pnpm ldraw:setup`, { cause });
  }

  const colors = [];
  const seen = new Set();
  for (const line of text.split(LINE_BREAK)) {
    if (!COLOUR_DIRECTIVE.test(line.trim())) {
      continue;
    }
    const entry = parseColour(line.trim());
    if (!entry || seen.has(entry.code)) {
      continue;
    }
    seen.add(entry.code);
    colors.push(entry);
  }
  colors.sort((a, b) => a.code - b.code);

  const rows = colors
    .map((c) => {
      const fields = [
        `name: ${JSON.stringify(c.name)}`,
        `hex: '${c.hex}'`,
        c.edge ? `edge: '${c.edge}'` : null,
        c.alpha === undefined ? null : `alpha: ${c.alpha}`,
        c.finish ? `finish: '${c.finish}'` : null,
      ].filter(Boolean);
      return `  ${c.code}: { ${fields.join(", ")} },`;
    })
    .join("\n");

  const out = `// Generated by scripts/gen-colors.mjs from the LDraw library's LDConfig.ldr.
// Do not edit by hand. Regenerate with: pnpm ldraw:colors
//
// LDraw colour definitions are part of the LDraw Parts Library, CC BY 2.0.
// https://www.ldraw.org/

type LDrawColorFinish =
  | 'chrome'
  | 'metal'
  | 'pearlescent'
  | 'rubber'
  | 'matte_metallic'

interface LDrawColor {
  name: string
  hex: string
  edge?: string
  /** 0-255. Present only for translucent colours. */
  alpha?: number
  finish?: LDrawColorFinish
}

const LDRAW_COLORS: Record<number, LDrawColor> = {
${rows}
}

export function colorName(code: number): string {
  // Code 16 means "inherit from the parent".
  if (code === 16) return 'Inherited'
  return LDRAW_COLORS[code]?.name ?? \`Colour \${code}\`
}

export function colorHex(code: number): string {
  return LDRAW_COLORS[code]?.hex ?? '#FF00FF'
}

export function isTranslucent(code: number): boolean {
  const alpha = LDRAW_COLORS[code]?.alpha
  return alpha !== undefined && alpha < 255
}
`;

  await writeFile(OUT, out);
  console.log(
    `- wrote ${path.relative(process.cwd(), OUT)} with ${colors.length} colours`
  );
}

main().catch((err) => {
  console.error(`gen-colors failed: ${err.message}`);
  process.exit(1);
});
