#!/usr/bin/env node
// Writes the two demo models in demo-models/, then leave packing to
// `pnpm ldraw:pack`.
//
// The LDraw library ships only two sample models (car and pyramid). Both are
// small, both are single-file, and both carry authored `0 STEP` metas, so
// nothing bundled exercises two features that matter: inferring a build order
// for a file that has none, and navigating a model made of submodels. Rather
// than redistribute somebody's recreation of a real set, these are generated
// from library parts.
//
// LDraw geometry notes, verified by measuring the parts:
//   - Y points DOWN, so stacking upward means decreasing y.
//   - A brick's origin is the centre of its top face; it occupies y 0..24.
//   - Brick height 24, plate height 8, one stud pitch 20.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { ROOT } from "./lib/paths.mjs";

const OUT_DIR = path.join(ROOT, "demo-models");

const BRICK = 24;
const PLATE = 8;
const STUD = 20;

const IDENTITY = "1 0 0 0 1 0 0 0 1";
const ROT_Y90 = "0 0 1 0 1 0 -1 0 0";

const STEP_LINE = /^0 STEP/;

const COLOR = {
  blue: 1,
  darkGrey: 72,
  green: 2,
  lightGrey: 71,
  red: 4,
  white: 15,
  yellow: 14,
};

/** One type-1 reference line. */
const ref = (colour, x, y, z, file, matrix = IDENTITY) =>
  `1 ${colour} ${x} ${y} ${z} ${matrix} ${file}`;

// ---------------------------------------------------------------------------
// Demo 1: a wall with no build steps at all.
//
// No `0 STEP` metas, so opening it exercises the inferred build order. Running
// bond interlocks the courses, so a bottom-to-top guess is visibly right.
// ---------------------------------------------------------------------------
function buildWall() {
  const lines = [
    "0 Running Bond Wall",
    "0 Name: wall.ldr",
    "0 Author: Generated by scripts/make-demos.mjs",
    "0 // No STEP metas: this model exists to exercise inferred build order.",
    "",
  ];

  const courses = 7;
  const bricksPerCourse = 4;
  const brickWidth = 4 * STUD; // 3001, Brick 2 x 4
  const halfWidth = 2 * STUD; // 3003, Brick 2 x 2
  const accent = [COLOR.red, COLOR.yellow, COLOR.blue];

  for (let course = 0; course < courses; course += 1) {
    const y = -course * BRICK;
    const offset = course % 2 === 1;
    // Every third course gets a colour band, so the parts bin has something to
    // group and the inferred steps are easy to tell apart.
    const base = course % 3 === 0 ? COLOR.white : COLOR.lightGrey;

    if (offset) {
      // Offset courses start and end with a half brick to keep the ends flush.
      lines.push(
        ref(
          accent[course % accent.length],
          -1.5 * brickWidth - halfWidth / 2,
          y,
          0,
          "3003.dat"
        )
      );
    }

    for (let i = 0; i < bricksPerCourse; i += 1) {
      const x =
        (i - (bricksPerCourse - 1) / 2) * brickWidth + (offset ? halfWidth : 0);
      const colour =
        i === course % bricksPerCourse ? accent[course % accent.length] : base;
      lines.push(ref(colour, x, y, 0, "3001.dat"));
    }

    if (offset) {
      lines.push(
        ref(
          accent[course % accent.length],
          1.5 * brickWidth + halfWidth / 2 + halfWidth,
          y,
          0,
          "3003.dat"
        )
      );
    }
  }

  // A tile coping along the top, so the wall has a finished edge.
  const topY = -courses * BRICK;
  for (let i = 0; i < bricksPerCourse; i += 1) {
    const x = (i - (bricksPerCourse - 1) / 2) * brickWidth;
    lines.push(ref(COLOR.darkGrey, x, topY, 0, "3020.dat"));
  }

  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Demo 2: a gatehouse built from named submodels, with real build steps.
//
// Four towers and a wall span, each its own submodel, so the submodel tree has
// something to isolate and bag labels have something to name themselves after.
// ---------------------------------------------------------------------------
function buildGatehouse() {
  const files = [];

  const tower = () => {
    const lines = ["0 Tower", "0 Name: tower.ldr", "0 !LDRAW_ORG Model", ""];
    for (let level = 0; level < 6; level += 1) {
      const y = -level * BRICK;
      const colour = level < 4 ? COLOR.lightGrey : COLOR.darkGrey;
      lines.push(ref(colour, -STUD, y, -STUD, "3005.dat"));
      lines.push(ref(colour, STUD, y, -STUD, "3005.dat"));
      lines.push(ref(colour, -STUD, y, STUD, "3005.dat"));
      lines.push(ref(colour, STUD, y, STUD, "3005.dat"));
      // A step every two levels: enough steps to scrub through, few enough
      // that each one places a visible amount.
      if (level % 2 === 1) {
        lines.push("0 STEP");
      }
    }
    // Battlements.
    const topY = -6 * BRICK;
    lines.push(ref(COLOR.darkGrey, -STUD, topY, -STUD, "3024.dat"));
    lines.push(ref(COLOR.darkGrey, STUD, topY, STUD, "3024.dat"));
    lines.push("0 STEP");
    return `${lines.join("\n")}\n`;
  };

  const span = () => {
    const lines = ["0 Wall Span", "0 Name: span.ldr", "0 !LDRAW_ORG Model", ""];
    for (let course = 0; course < 3; course += 1) {
      const y = -course * BRICK;
      for (let i = -1; i <= 1; i += 1) {
        lines.push(
          ref(
            course === 2 ? COLOR.red : COLOR.white,
            i * 4 * STUD,
            y,
            0,
            "3001.dat"
          )
        );
      }
      lines.push("0 STEP");
    }
    return `${lines.join("\n")}\n`;
  };

  const base = () => {
    const lines = ["0 Courtyard", "0 Name: base.ldr", "0 !LDRAW_ORG Model", ""];
    for (let row = -2; row <= 2; row += 1) {
      for (let col = -1; col <= 1; col += 1) {
        lines.push(
          ref(COLOR.green, col * 4 * STUD, 0, row * 2 * STUD, "3020.dat")
        );
      }
      lines.push("0 STEP");
    }
    return `${lines.join("\n")}\n`;
  };

  const gatehouse = () => {
    const lines = [
      "0 Gatehouse",
      "0 Name: gatehouse.ldr",
      "0 Author: Generated by scripts/make-demos.mjs",
      "0 !LDRAW_ORG Model",
      "",
      ref(COLOR.white, 0, 0, 0, "base.ldr"),
      "0 STEP",
    ];
    // Four corner towers, then the span across the front.
    const baseTop = -PLATE;
    for (const [x, z] of [
      [-140, -100],
      [140, -100],
      [-140, 100],
      [140, 100],
    ]) {
      lines.push(ref(COLOR.white, x, baseTop, z, "tower.ldr"));
      lines.push("0 STEP");
    }
    lines.push(ref(COLOR.white, 0, baseTop, -100, "span.ldr", ROT_Y90));
    lines.push("0 STEP");
    return `${lines.join("\n")}\n`;
  };

  // MPD ordering matters: the first `0 FILE` block is the model that gets loaded.
  files.push(["gatehouse.ldr", gatehouse()]);
  files.push(["base.ldr", base()]);
  files.push(["tower.ldr", tower()]);
  files.push(["span.ldr", span()]);

  return files.map(([name, body]) => `0 FILE ${name}\n${body}`).join("\n");
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const outputs = [
    ["wall.ldr", buildWall()],
    ["gatehouse.mpd", buildGatehouse()],
  ];

  await Promise.all(
    outputs.map(([name, body]) => writeFile(path.join(OUT_DIR, name), body))
  );

  for (const [name, body] of outputs) {
    const refs = body.split("\n").filter((l) => l.startsWith("1 ")).length;
    const steps = body.split("\n").filter((l) => STEP_LINE.test(l)).length;
    console.log(
      `- ${name.padEnd(16)} ${String(refs).padStart(4)} refs, ${steps} STEP metas`
    );
  }
  console.log("\nNow run: pnpm ldraw:pack");
}

main().catch((err) => {
  console.error(`make-demos failed: ${err.message}`);
  process.exit(1);
});
