#!/usr/bin/env node
// Packs the bundled sample models into self-contained .mpd files under
// public/models, alongside a manifest the gallery reads.
//
//   pnpm ldraw:pack                 pack the curated list
//   pnpm ldraw:pack --omr 928-1     pack an Official Model Repository set
//   pnpm ldraw:pack path/to/x.ldr   pack one extra file into the gallery
//   pnpm ldraw:pack x.ldr --skip-missing   drop parts that cannot be resolved
//
// Requires the parts library (pnpm ldraw:setup). Outputs are committed, so a
// plain checkout can run the app without ever touching the library.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { analyze } from "./lib/ldraw-analyze.mjs";
import { fetchSet } from "./lib/omr.mjs";

const MODEL_EXTENSION = /\.(ldr|mpd|dat)$/i;

import {
  buildLibraryIndex,
  localResolver,
  packModel,
} from "./lib/ldraw-pack.mjs";
import { LIBRARY_DIR, PUBLIC_MODELS_DIR } from "./lib/paths.mjs";

// Only models we are allowed to redistribute: the two samples that ship inside
// the LDraw library under CC BY 2.0, plus two generated by scripts/make-demos.mjs
// that cover cases the samples do not (inferred build order, submodels).
//
// Paths in `file` resolve against the library folder, so the generated models
// reach back out of it with `../demo-models`.
const CURATED = [
  {
    blurb: "Has no build steps of its own, so the order is inferred bottom-up.",
    credit: "Generated, from LDraw library parts (CC BY 2.0)",
    file: "../demo-models/wall.ldr",
    slug: "wall",
    title: "Running Bond Wall",
  },
  {
    blurb:
      "Four towers and a span, each its own submodel to isolate and inspect.",
    credit: "Generated, from LDraw library parts (CC BY 2.0)",
    file: "../demo-models/gatehouse.mpd",
    slug: "gatehouse",
    title: "Gatehouse",
  },
  {
    blurb: "The canonical LDraw demo model. Eight authored build steps.",
    credit: "James Jessiman, LDraw library (CC BY 2.0)",
    file: "models/car.ldr",
    slug: "car",
    title: "Example Car",
  },
  {
    blurb:
      "A four-step stack. The smallest thing that still shows build order.",
    credit: "James Jessiman, LDraw library (CC BY 2.0)",
    file: "models/pyramid.ldr",
    slug: "pyramid",
    title: "Example Pyramid",
  },
  // Real LEGO sets from the Official Model Repository. Redistributable under
  // CCAL 2.0 with attribution, which the packer reads out of each file.
  {
    blurb:
      "Classic Space, 1979. Fifty-three build steps as its author wrote them.",
    omr: "928-1",
    slug: "galaxy-explorer",
    title: "928 Galaxy Explorer",
  },
  {
    blurb: "Eighteen hundred bricks over seven hundred steps, split into bags.",
    omr: "21309-1",
    slug: "saturn-v",
    title: "21309 NASA Apollo Saturn V",
  },
];

/**
 * Load one job's model text. A curated OMR entry is fetched and checked for its
 * redistribution licence; everything else is a file on disk.
 */
async function readSource(job) {
  if (!job.omr) {
    return readFile(job.source, "utf8").then(
      (text) => ({ job, text }),
      () => ({ job, text: null })
    );
  }

  try {
    const { text, metadata } = await fetchSet(job.omr);
    if (!metadata.redistributable) {
      // No CCAL header means no licence to ship it.
      console.error(
        `  FAIL ${job.slug}: ${job.omr} carries no CCAL licence header`
      );
      return { job, text: null };
    }
    return {
      job: {
        ...job,
        author: metadata.author,
        credit: `${metadata.author ?? "Unknown author"}, LDraw OMR (CC BY 2.0)`,
        theme: metadata.theme,
      },
      text,
    };
  } catch (error) {
    console.error(`  FAIL ${job.slug}: ${error.message}`);
    return { job, text: null };
  }
}

/**
 * Log whatever went wrong with one pack. Returns true when the model must be
 * treated as a failure rather than shipped.
 */
function reportPackProblems(job, missing, stats, skipMissing) {
  if (missing.length > 0 && !skipMissing) {
    // A silently incomplete pack renders as invisible bricks at runtime, which
    // is far worse to debug than a loud failure here.
    console.error(
      `  FAIL ${job.slug}: ${missing.length} unresolved reference(s)`
    );
    for (const ref of missing.slice(0, 10)) {
      console.error(`        ${ref}`);
    }
    console.error(
      "        pass --skip-missing to build the model without them"
    );
    return true;
  }

  if (missing.length > 0) {
    console.warn(
      `  warn ${job.slug}: skipped ${stats.skipped} reference(s) to ${missing.length} unresolved part(s)`
    );
  }
  if (stats.texmapFiles.length > 0) {
    console.warn(
      `  warn ${job.slug}: ${stats.texmapFiles.length} file(s) use !TEXMAP, which LDrawLoader ignores`
    );
  }
  return false;
}

const slugify = (name) =>
  path
    .basename(name)
    .replace(MODEL_EXTENSION, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

async function main() {
  const argv = process.argv.slice(2);
  const skipMissing = argv.includes("--skip-missing");
  const extra = argv.filter((arg) => !arg.startsWith("--"));

  let index;
  try {
    ({ index } = await buildLibraryIndex(LIBRARY_DIR));
  } catch (cause) {
    throw new Error(`could not read ${LIBRARY_DIR}. Run: pnpm ldraw:setup`, {
      cause,
    });
  }
  if (index.size === 0) {
    throw new Error(`${LIBRARY_DIR} is empty. Run: pnpm ldraw:setup`);
  }
  console.log(`- indexed ${index.size} library files`);
  const resolve = localResolver(index);

  await mkdir(PUBLIC_MODELS_DIR, { recursive: true });

  const jobs = [
    ...CURATED.map((entry) =>
      entry.omr
        ? { ...entry, source: `OMR ${entry.omr}` }
        : { ...entry, source: path.join(LIBRARY_DIR, entry.file) }
    ),
    ...extra.map((file) => ({
      blurb: "",
      credit: "User supplied",
      slug: slugify(file),
      source: path.resolve(file),
      title: path.basename(file).replace(MODEL_EXTENSION, ""),
      userSupplied: true,
    })),
  ];

  // Preserve gallery entries from previous runs (e.g. models packed one-off)
  // so packing a new model does not silently drop the others.
  const manifestPath = path.join(PUBLIC_MODELS_DIR, "manifest.json");
  const existing = new Map();
  try {
    const prev = JSON.parse(await readFile(manifestPath, "utf8"));
    for (const entry of prev.models ?? []) {
      existing.set(entry.slug, entry);
    }
  } catch {
    // no manifest yet
  }

  // Read every source first. The loop below logs one line per model in order,
  // so it must stay sequential; the file reads do not have to be.
  const sources = await Promise.all(jobs.map((job) => readSource(job)));

  // Packing is independent per model given the shared index, so it all happens
  // before the reporting loop, which has to stay ordered to read sensibly.
  const packed = await Promise.all(
    sources.map(async ({ job, text }) => {
      if (text === null) {
        return { job, result: null };
      }
      return {
        job,
        result: await packModel({
          name: job.omr ? `${job.omr}.mpd` : path.basename(job.source),
          resolve,
          skipMissing,
          text,
        }),
      };
    })
  );

  let failures = 0;
  for (const { job, result } of packed) {
    if (result === null) {
      console.error(`  FAIL ${job.slug}: cannot read ${job.source}`);
      failures += 1;
      continue;
    }

    const { mpd, partNames, missing, stats } = result;

    if (reportPackProblems(job, missing, stats, skipMissing)) {
      failures += 1;
      continue;
    }

    const info = analyze(mpd);

    // biome-ignore lint/performance/noAwaitInLoops: the loop reports one line per model in order, so it stays sequential; the two writes inside it do not
    await Promise.all([
      writeFile(path.join(PUBLIC_MODELS_DIR, `${job.slug}.mpd`), mpd),
      writeFile(
        path.join(PUBLIC_MODELS_DIR, `${job.slug}.parts.json`),
        JSON.stringify(partNames)
      ),
    ]);

    existing.set(job.slug, {
      author: job.author ?? null,
      blurb: job.blurb,
      bricks: info.bricks,
      bytes: stats.bytes,
      credit: job.credit,
      slug: job.slug,
      steps: info.steps,
      theme: job.theme ?? null,
      title: job.title,
      uniqueParts: info.uniqueParts,
      userSupplied: job.userSupplied ?? false,
    });

    console.log(
      `  ok   ${job.slug.padEnd(14)} ${String(info.bricks).padStart(5)} bricks  ` +
        `${String(info.steps).padStart(3)} steps  ${String(info.uniqueParts).padStart(4)} unique  ` +
        `${(stats.bytes / 1024).toFixed(0)}KB  (${stats.files} files inlined)`
    );
  }

  const models = [...existing.values()].sort((a, b) => a.bricks - b.bricks);
  await writeFile(
    manifestPath,
    `${JSON.stringify({ generatedAt: new Date().toISOString(), models }, null, 2)}\n`
  );
  console.log(`- wrote manifest with ${models.length} model(s)`);

  if (failures > 0) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(`pack failed: ${err.message}`);
  process.exit(1);
});
